### ISSUE TITLE
A bit of an issue with the background

### ISSUE THREAD

**Issue by pierrelouys** [joel16/NTPSP#1]
![20221008223051](https://user-images.githubusercontent.com/75588890/194845984-179d5e51-298c-4e61-8501-4eb74f886a6c.png)

PSP-1004 6.61 LME 2.3, no custom themes. 

The app worked great aside from the graphical glitch though.

**Comment by joel16** [comment]
I tried fixing this but it seems impossible. Seems like a bug related to the vlflib it self, and thus I've decided to just set a fixed colour instead of it trying to pick the user's XMB colour and  failing (defaulting to black) like in your screenshot. Anyways fixed with: https://github.com/joel16/NTPSP/commit/06b709fb4f9a3597031157c81f466ffab4ecac1b
